name: Go
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make build

    - name: Deploy
      run: |
        set -e
        remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        remote_branch="gh-pages"
        rm -rf gh-pages
        git clone --branch $remote_branch $remote_repo gh-pages
        cp index.html main.wasm wasm_exec.js README.md gh-pages
        pushd gh-pages
        git add --all
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git commit --allow-empty -m "auto build $(date -u) ${GITHUB_SHA}"
        git push origin "${remote_branch}"
        echo 'Deploy SUCCESS!'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

